### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by phantomsamurai** [Draichi/altcoin-bot-advisor#1]
[1m[31mUsage: python3 train.py [asset] [window] [episodes][0m

None
Stack trace:
 >  File "C:\Users\Amelize\Downloads\DL\New folder\cryptocurrency_prediction-masterDraichi\cryptocurrency_prediction-master\train.py", line 5, in <module>
 >    exit()
Loaded '__main__'
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_local.py", line 125, in _run
    
_pydevd.main()

  File "c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 1752, in main
    
globals = debugger.run(setup['file'], None, None, is_module)

  File "c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 1099, in run
    
return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)

  File "c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 1106, in _exec
    
pydev_imports.execfile(file, globals, locals)  # execute the script

  File "c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    
exec(compile(contents+"\n", file, 'exec'), glob, loc)

  File "C:\Users\Amelize\Downloads\DL\New folder\cryptocurrency_prediction-masterDraichi\cryptocurrency_prediction-master\train.py", line 5, in <module>
    
exit()

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\_sitebuiltins.py", line 26, in __call__
    
raise SystemExit(code)

SystemExit
: 
None

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    
vspd.debug(filename, port_num, debug_id, debug_options, run_as)

  File "c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 37, in debug
    
run(address, filename, *args, **kwargs)

  File "c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_local.py", line 64, in run_file
    
run(argv, addr, **kwargs)

  File "c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_local.py", line 127, in _run
    
daemon.exitcode = int(ex.code)

TypeError
: 
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

The thread 'MainThread' (0x1) has exited with code 0 (0x0).

**Comment by Draichi** [comment]
same #2
