### ISSUE TITLE
TensorboardX failed to log hparams

### ISSUE THREAD

**Issue by tyronehunt** [Draichi/altcoin-bot-advisor#18]
Hi again @Draichi. I've moved on from https://github.com/Draichi/Stock-Trading-Visualization (although I must admit, it's always frustrating to leave behind a code base without getting it running). 

This new code is throwing errors:
1. from ray.rllib.evaluation.episode import  _flatten_action (cannot import _flatten_action)
2. when running main.py I get the following error and then my 3 trials terminate. I'm unclear if the below error is even related to the trials terminating to be honest.

`ERROR logger.py:281 -- TensorboardX failed to log hparams. This may be due to an unsupported type in the hyperparameter values.
Traceback (most recent call last):
  File "/Users/xxx/xxx/xxx/xxx/env/lib/python3.6/site-packages/ray/tune/logger.py", line 276, in _try_log_hparams
    hparam_dict=scrubbed_params, metric_dict=result)
  File "/Users/xxx/xxx/xxx/xxx/env/lib/python3.6/site-packages/tensorboardX/summary.py", line 103, in hparams
    ssi.hparams[k].number_value = v
TypeError: array([0.e+00, 5.e-05]) has type numpy.ndarray, but expected one of: int, long, float
2020-05-26 23:42:29,556	WARNING util.py:137 -- The `process_trial` operation took 1.1992979049682617 seconds to complete, which may be a performance bottleneck.`

**Comment by Draichi** [comment]
What's your os?

**Comment by tyronehunt** [comment]
I'm on MacOS Mojave 10.14.6. Thanks for your patience on this. I'd really love to get something up and running, so that I can start trying to improve on it!
